apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    part-of: breathe.io
spec:
  selector:
    app: postgres-pod
    part-of: breathe.io
  ports:
    - port: 5432
      targetPort: 5432
  