// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SubPaymentClient is the client API for SubPayment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubPaymentClient interface {
	CreateUserSubcription(ctx context.Context, in *CreateUserSubcriptionReq, opts ...grpc.CallOption) (*CreateUserSubcriptionResp, error)
	GetUserSubcriptions(ctx context.Context, in *GetUserSubcriptionsReq, opts ...grpc.CallOption) (*GetUserSubcriptionsResp, error)
	CompletePayment(ctx context.Context, in *CompletePaymentReq, opts ...grpc.CallOption) (*CompletePaymentResp, error)
}

type subPaymentClient struct {
	cc grpc.ClientConnInterface
}

func NewSubPaymentClient(cc grpc.ClientConnInterface) SubPaymentClient {
	return &subPaymentClient{cc}
}

func (c *subPaymentClient) CreateUserSubcription(ctx context.Context, in *CreateUserSubcriptionReq, opts ...grpc.CallOption) (*CreateUserSubcriptionResp, error) {
	out := new(CreateUserSubcriptionResp)
	err := c.cc.Invoke(ctx, "/sub_payment.SubPayment/CreateUserSubcription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subPaymentClient) GetUserSubcriptions(ctx context.Context, in *GetUserSubcriptionsReq, opts ...grpc.CallOption) (*GetUserSubcriptionsResp, error) {
	out := new(GetUserSubcriptionsResp)
	err := c.cc.Invoke(ctx, "/sub_payment.SubPayment/GetUserSubcriptions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subPaymentClient) CompletePayment(ctx context.Context, in *CompletePaymentReq, opts ...grpc.CallOption) (*CompletePaymentResp, error) {
	out := new(CompletePaymentResp)
	err := c.cc.Invoke(ctx, "/sub_payment.SubPayment/CompletePayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubPaymentServer is the server API for SubPayment service.
// All implementations must embed UnimplementedSubPaymentServer
// for forward compatibility
type SubPaymentServer interface {
	CreateUserSubcription(context.Context, *CreateUserSubcriptionReq) (*CreateUserSubcriptionResp, error)
	GetUserSubcriptions(context.Context, *GetUserSubcriptionsReq) (*GetUserSubcriptionsResp, error)
	CompletePayment(context.Context, *CompletePaymentReq) (*CompletePaymentResp, error)
	mustEmbedUnimplementedSubPaymentServer()
}

// UnimplementedSubPaymentServer must be embedded to have forward compatible implementations.
type UnimplementedSubPaymentServer struct {
}

func (UnimplementedSubPaymentServer) CreateUserSubcription(context.Context, *CreateUserSubcriptionReq) (*CreateUserSubcriptionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserSubcription not implemented")
}
func (UnimplementedSubPaymentServer) GetUserSubcriptions(context.Context, *GetUserSubcriptionsReq) (*GetUserSubcriptionsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserSubcriptions not implemented")
}
func (UnimplementedSubPaymentServer) CompletePayment(context.Context, *CompletePaymentReq) (*CompletePaymentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompletePayment not implemented")
}
func (UnimplementedSubPaymentServer) mustEmbedUnimplementedSubPaymentServer() {}

// UnsafeSubPaymentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubPaymentServer will
// result in compilation errors.
type UnsafeSubPaymentServer interface {
	mustEmbedUnimplementedSubPaymentServer()
}

func RegisterSubPaymentServer(s grpc.ServiceRegistrar, srv SubPaymentServer) {
	s.RegisterService(&SubPayment_ServiceDesc, srv)
}

func _SubPayment_CreateUserSubcription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserSubcriptionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubPaymentServer).CreateUserSubcription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sub_payment.SubPayment/CreateUserSubcription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubPaymentServer).CreateUserSubcription(ctx, req.(*CreateUserSubcriptionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubPayment_GetUserSubcriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSubcriptionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubPaymentServer).GetUserSubcriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sub_payment.SubPayment/GetUserSubcriptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubPaymentServer).GetUserSubcriptions(ctx, req.(*GetUserSubcriptionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubPayment_CompletePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompletePaymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubPaymentServer).CompletePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sub_payment.SubPayment/CompletePayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubPaymentServer).CompletePayment(ctx, req.(*CompletePaymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SubPayment_ServiceDesc is the grpc.ServiceDesc for SubPayment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubPayment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sub_payment.SubPayment",
	HandlerType: (*SubPaymentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUserSubcription",
			Handler:    _SubPayment_CreateUserSubcription_Handler,
		},
		{
			MethodName: "GetUserSubcriptions",
			Handler:    _SubPayment_GetUserSubcriptions_Handler,
		},
		{
			MethodName: "CompletePayment",
			Handler:    _SubPayment_CompletePayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sub-payment.proto",
}
